### ISSUE TITLE
Please, update version 2.2, and upload the new Tail version if possible.

### ISSUE THREAD

**Issue by Dhyfer1** [YT-Advanced/Windows-11-Cursor-by-rosea92#2]
Hi

Thanks for your contribution, but the author of the cursors has created 3 new variants (purple, sunset and candy) of version 2.2 as you can see [here](https://www.deviantart.com/jepricreations/art/Windows-11-Cursors-Concept-HD-v2-890672103). The last update of the cursors pack was on March 3rd, could you please re-upload the updated version with these 3 new cursors?

Also, the author has created a new cursor pack called Tail, [paid](https://www.deviantart.com/jepricreations/art/Preview-962242774) version and [free](https://www.deviantart.com/jepricreations/art/Windows-11-Free-Tail-Cursor-Concept-962242647) version. Can you get the paid version of Tail cursors and share it?

That's all.

**Comment by YT-Advanced** [comment]
@Dhyfer1 I have updated. Can you check it ?

**Comment by Dhyfer1** [comment]
WOW!! Thank you very much for upgrading to the latest version, you are my hero without a cape! 😅

Have you seen the Tail Cursor Pack by the same author? Do you think you can get the paid version and share it?

**Comment by YT-Advanced** [comment]
@Dhyfer1 I have updated Tail Cursor Pack to this link, you can download it now:
https://github.com/YT-Advanced/Windows-11-Cursor-Tail-by-roses92/

**Comment by Dhyfer1** [comment]
> @Dhyfer1 I have updated Tail Cursor Pack to this link, you can download it now:
> https://github.com/YT-Advanced/Windows-11-Cursor-Tail-by-roses92/

@YT-Advanced Thank you very much for sharing! Thanks for uploading this version, a long time ago I was looking for this pack in other places but I couldn't find anything. Now thanks to you I already have the paid version, thank you very much again. 😊
