### ISSUE TITLE
Is it definitley on the latest version?

### ISSUE THREAD

**Issue by SirEthanator** [YT-Advanced/Windows-11-Cursor-by-rosea92#3]
I have seen that the default color of the dark loading spinner is not changed here like it is here: https://www.deviantart.com/jepricreations/art/Windows-11-Cursors-Concept-HD-v2-890672103
If possible can you update so this change is here?

**Comment by YT-Advanced** [comment]
What do you mean, I have updated the cursors to the latest

**Comment by SirEthanator** [comment]
This is the color when I download it: 
![image](https://github.com/YT-Advanced/Windows-11-Cursor-by-rosea92/assets/130725768/d013cf05-d513-445e-8f64-76191603b705)
And this is the color I expect:
![image](https://github.com/YT-Advanced/Windows-11-Cursor-by-rosea92/assets/130725768/7647167f-8d7a-4e35-b986-b814991c98f2)

**Comment by YT-Advanced** [comment]
hmm, maybe the author have updated this cursor

**Comment by SirEthanator** [comment]
Any chance you can re-download and see if that fixes it?

**Comment by YT-Advanced** [comment]
Hmm, here is drive link, can you test this:
https://drive.google.com/file/d/17ef2_iyXrnBs6c-QXEavUuOi7NHPewwH/view?usp=drive_link

**Comment by SirEthanator** [comment]
It still doesn't seem to be up to date. Have you tried re-downloading from ko-fi/deviantart?

**Comment by YT-Advanced** [comment]
Hmm, I don't know what you are menainf because I have updated the latest from kofi. You can pay it and check, all are the same
